index:
    path:     /
    defaults: {_controller: AppBundle:Default:index}
blog:
    path:     /products
    defaults: { _controller: AppBundle:Blog:index }
post:
    path:     /products/{id}
    defaults: { _controller: AppBundle:Blog:show, id: id }
    requirements: 
        id: \d+
about:
    path:     /about
    defaults: { _controller: AppBundle:About:index }
contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:index }
send_message:
    path:     /contact/send
    defaults: { _controller: AppBundle:Contact:post }
    methods:  [POST]
recommendation:
    path:     /recommendation
    defaults: { _controller: AppBundle:Recommended:index }

artists:
    path:     /artists
    defaults: { _controller: AppBundle:Artist:index }

show:
    path:     /artists/{slug}
    defaults: { _controller: AppBundle:Artist:show, slug: slug }

genres:
    path:     /genres
    defaults: { _controller: AppBundle:Genre:index }

atoz:
    path:     /a-to-z
    defaults: { _controller: AppBundle:AToZ:index }

order:
    path:     /order/{id}
    defaults: { _controller: AppBundle:Order:show, id:id }

order_options:
    path:     /order/{id}/payment
    defaults: { _controller: AppBundle:Order:post, id:id }

user:
    path:     /user
    defaults: {_controller: AppBundle:User:show}
    methods:  [GET]

login:
    path:     /login
    defaults: {_controller: AppBundle:User:index}
    methods:  [GET]

logout:
    path:     /logout
    defaults: {_controller: AppBundle:User:logout}

post_login:
    path:     /login
    defaults: { _controller: AppBundle:User:post }
    methods:  [POST]
