index:
    path:     /
    defaults: {_controller: AppBundle:Default:index}
blog:
    path:     /products
    defaults: { _controller: AppBundle:Blog:index }
post:
    path:     /products/{id}
    defaults: { _controller: AppBundle:Blog:show, id: id }
    requirements: 
        id: \d+
about:
    path:     /about
    defaults: { _controller: AppBundle:About:index }
contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:index }
send_message:
    path:     /contact/send
    defaults: { _controller: AppBundle:Contact:post }
    methods:  [POST]