<?php

namespace AppBundle\Entity;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByFirstLetter($letter)
	{
		// $qb = $this->createQueryBuilder('u');

		return $this->getEntityManager()
					->createQuery('SELECT a FROM AppBundle:Artist a WHERE a.name LIKE :letter')
					->setParameter('letter',$letter.'%')->getResult();
	}
}
