<?php

namespace AppBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByTitle()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Post p ORDER BY p.title ASC'
            )
            ->getResult();
    }

    public function findAllWithTagName($tag)
	{
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT p, t FROM AppBundle:Post p LEFT JOIN p.tags t WHERE t.name = :name'
	    	)->setParameter('name', $tag);
	    try {
	        return $query->getResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}
